name: Build and Test SRLinker

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install build-essential
      run: sudo apt-get install -y build-essential

    - name: Build project with gcc
      run: |
        gcc -o SRLinker main.c Root.c Actions/Backup.c Actions/AuxiliaryFunctions.c Actions/DeviceInfos.c Logo/Logo.c